name: test deploy-commands.js

on:
  push:
    branches:
      - master
      - feat/github-action

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: node js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: creating config.json
        run: touch ./config.json
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - run: 'echo {    "token": "$env:TOKEN",    "clientId": "$env:CLIENT_ID",    "guildId": "$env:GUILD_ID",    "apiToken": "$env:API_TOKEN"} >> ./config.json'
      - name: install dependencies
        run: npm ci
      - name: install dependencies
        run: npm install
      - run: node deploy-commands.js
