name: node js cli

on:
  push:
    branches: [feat/github-action]
  pull_request:
    branches: [feat/github-action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: node js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
      - run: npm install
      - run: node deploy-commands.js
